import ProductCard from "./productCard";
import BrandTab from "./BrandTab";
import { useState } from "react";

export default function AccessoriesListing() {

  const accessories = [
    {

    "_id": "12112231",
    "type": "Earbuds",
    "brand": "Apple",
    "name": "Apple AirPods Pro (2nd Generation) ",
    "price":  69999,
    "image":"https://www.simplytek.lk/cdn/shop/files/AIRPODS-Pro-2nd-gen-simplytek-lk-1.png?v=1694426217&width=1220",
    "pointdesc": "Upgraded audio with comfort , active noise cancellation and Magsafe convenience" ,
    "description": "The Apple AirPods Pro is one of Apple's latest innovations towards a greater listening experience with personalized spatial audio and dynamic head tracking",
    "warranty": "1 Year Apple Care"

},

{"_id": "435345",
"type": "Bluetooth Speakers",
"brand": "JBL",
"name": "JBL PartyBox 320",
"price":  164990,
"image":"https://idealz.lk/wp-content/uploads/2025/05/JBL-320-1.jpg",
"pointdesc": "Unlock your party sensation  with loud JBL pro sounds and a futuristic lightshow" ,
"description": "The JBL PartyBox 320 is the trendy spotlight with a high-powered 240W JBL Pro Sound with twin 6.5 woofers featuring a magnificent RGB lightshow syncing to your taste of music ",
"warranty": "6 Months Warranty"
},

{"_id": "23245512",
"type": "Bluetooth Speakers",
"brand": "Xiaomi",
"name": "Xiaomi Mi Sound Outdoor 30W Bluetooth Speaker",
"price":  12499,
"image":"https://www.simplytek.lk/cdn/shop/files/Xiaomi-outdoor-30w-Red-simplytek.png?v=1740657361&width=1220",
"pointdesc": "Built with a stable Bluetooth 5.4 connection with Wireless Stereo Sound",
"description": "The Xiaomi Mi Sound Outdoor 30W Bluetooth Speaker ignites crisp room-filling sound upto 30W with dynamic bass generated by dual woofers and allows smart volume changing - with endurance to dust and water resistance with a light 597g of body  ",
"warranty": "6 Months Warranty"
},

{"_id": "2324324324",
"type": "Powerbanks",
"brand": "Xiaomi",
"name": "Xiaomi Mi 20000mAh 50w PowerBank",
"price":  10990,
"image":"https://www.simplytek.lk/cdn/shop/files/Xiaomi-Mi-20000mAh-50w-PowerBank-Sri-Lanka-SimplyTek-1.jpg?v=1694425626&width=1220",
"pointdesc": "Multi-device charging model with USB Type-C two fast way charging"  ,
"description": "The Xiaomi Mi 20000mAh 50w model by Xiaomi packs a whopping 74Wh battery and delivers a rapid 50W USB-C output for smartphones separately - Furthermore it allows charging of three devices at once consecutively with dual USB-A and USB-C ports ",
"warranty": "6 Months Warranty"
},

{"_id": "23423234",
"type": "Powerbanks",
"brand": "Baseus",
"name": "Baseus Adaman 10000mAh 22.5W Powerbank",
"price":  5999,
"image":"https://www.simplytek.lk/cdn/shop/files/Baseus-Adaman-10000mAh-22-2-simplytek-lk.jpg?v=1694426263&width=1220",
"pointdesc": "A metallic bold build with a powerful battery capacity of 1000mAh and multiple outputs" ,
"description": "The Baseus Adaman 10 000 mAh Power Bank fuses safe power-charging through 22.5W output suporting USB-PD standards allowing charging of devices at a faster rate",
"warranty": "6 Months Warranty"},

{

    "_id": "121223",
    "type": "Earbuds",
    "brand": "Samsung",
    "name": " Samsung Galaxy Buds FE",
    "price":  19990,
    "image":"https://idealz.lk/wp-content/uploads/2024/10/Galaxy-Buds-FE-1.jpg",
    "pointdesc": "Trendy earbuds with seamless pairing and active noise cancellation",
    "description": "The Samsung Galaxy Buds FE are  Samsung’s latest wireless earbuds offering active noise cancellation and a new wingtip design",
    "warranty": "06 Months Shop Warranty"

}
  ]
  const types = ["ALL", "Earbuds", "Bluetooth Speakers", "Cables", "Chargers", "Powerbanks"]

  const [selectedtypes, setSelectedtypes] = useState("ALL");

  const handleSelectedtypes = (types) => {
    setSelectedtypes(types);
  }

  const filteredaccessories = selectedtypes === "ALL" ? accessories : accessories.filter((accessories) => {
    return accessories.type.toLowerCase().includes(selectedtypes.toLowerCase());
  })

  return (
    <section className="px-8 py-3 ">
      <div className="mb-5">
        <h2 className="text-3xl md:text-4xl font-bold mb-4">
          Top trending Accessories
        </h2>
        <p className="text-lg text-muted-foreground">
          Choose the most reliable and effcient accessories here at Cellmart
        </p>
      </div>
      <div className="flex items-center gap-x-4">
        {
          types.map((types) => {
            return (<BrandTab selectedtypes={selectedtypes} name={types} onClick={handleSelectedtypes} />)
          })
        }
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mt-4">
        {
          filteredaccessories.map((product) => {
            return (<ProductCard key={product._id} product={product} />)
          })
        }
      </div>
    </section>
  );
}